# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
fabric.loom.multiProjectOptimisation=true

deps.yarn_mappings=[VERSIONED]
deps.fabric_loader=[VERSIONED]
deps.fabric_api=[VERSIONED]

deps.placeholder_api=[VERSIONED]
deps.player_data_api=[VERSIONED]
deps.fabric_permissions_api=[VERSIONED]